### PR TITLE
Add new logo and favicon

### PR DESCRIPTION
**Pull request by jignaciopm**
Add new logo and favicon OPEN EDX to **STAGE**:

Before:
Captura de pantalla de 2021-03-12 01-59-39 favicon
Captura de pantalla de 2021-03-12 01-59-24 logo
edx-logo-header other-logo

After:

favicon favicon

openedx-logo logo
edx-logo-header other-logo

### CODE REVIEW

**Comment by morenol** [comment]
I think that we should create a new branch. open-release/juniper.master is reserved for the actual release. For dpeloyments, we use the `release` branch.

**Review by AuraAlba — APPROVED** [review]

**Comment by morenol** [comment]
The insights logo says edX instead of openedx. Not sure if we can use that.

**Comment by jignaciopm** [comment]
@morenol I launched the merge to the juniper.master branch because according to what I understood from what happened to me Eric (SRE), that is the STAGE branch.

**Comment by morenol** [comment]
@ericfab179 we should use a different branch for stage now that we have custom modifications, we should keep open-release/juniper.master with the same that is has in upstream.
 
Maybe we need to create open-release/juniper.ednx

**Comment by ericfab179** [comment]
@morenol @jignaciopm Sure, actually the branch that is being deployed in Production is "release" and we want to keep Stage and Production as similar as possible so I think that you need to open this PR against that branch and deploy stage using that branch.

The default branch in stage was set to open-release/juniper.master but it was just a reference and in stage you are free to select/change the branch that you want to deploy. I am going to change the default value to "release" but feel free to change it in stage when you need to test or debug something.

**Review by morenol — APPROVED** [review]

**Comment by jignaciopm** [comment]
I see that @morenol  has approved the pr, but apparently I must close it and open it pointing to the branch 'release' correct? Sorry to ask, but it is not clear to me!

**Comment by morenol** [comment]
@jignaciopm I already changed the base branch in this PR. You can merge this PR and we are done!

**Pull request merged**
